### ISSUE TITLE
Reach a stable point where we can cut a release

### ISSUE THREAD

**Issue by stefanbucur** [bazelbuild/rules_fuzzing#113]
This is a meta-issue tracking the dependent issues needed so we can cut a release. Tentatively aiming for `v0.1`.

## Work items left

**OSS-Fuzz support:**

- [x] Add the `bazel-rules-fuzzing-test` project (google/oss-fuzz#4936).
- [x] Update the Github Actions here to do a CIFuzz run using `bazel-rules-fuzzing-test`.

**Envoy integration:**

- [x] Validate that the coverage support is still working.
- [x] Update the Envoy OSS-Fuzz project build script.
- [x] Fix the size bloat caused by the OSS-Fuzz package rule.
- [x] Resolve the disk space and build effort issue caused by the fuzzing instrumentation transition.

**Documentation:**

- [x] Update the OSS-Fuzz documentation to include Bazel guidance.
- [x] Clarify the asan-replay mode.
- [x] Move the extensibility documentation to a separate page.
- [x] Move the integration instructions to a separate page.
- [x] Document the launcher flags.

**Misc:**

- [ ] Announce the release.

**Comment by stefanbucur** [comment]
In particular, the release depends on wrapping up the OSS-Fuzz integration: #105 on our end, and submitting google/oss-fuzz#4936.
